### ISSUE TITLE
[ERROR] Parse JSON failed,

### ISSUE THREAD

**Issue by Nosreme1** [woblerr/pgbackrest_exporter#10] opened 2021-09-16 12:53 UTC
Hello,
First of all, thank you for developing this PGBackrest exporter.
When launching the pgbackrest_exporter service, I have the following error:
"[ERROR] Parse JSON failed, invalid character 'W' looking for beginning of value"
So,the metrics do not go up in Prometheus.
I'm using : pgBackRest 2.32
Do you have any idea how to solve the problem please?

**Comment by woblerr** [comment] 2021-09-16 18:04
Hi,
Please, provide additional information.
* pgbackrest_exporter version;
* Unit configuration file for pgbackrest_exporter service (for example, `pgbackrest_exporter.service`).
* If you start  pgbackrest_exporter from binary file (for example, `./pgbackrest_exporter`) the error is reproduced?
* Command output `pgbackrest info --output json`.

**Comment by Nosreme1** [comment] 2021-09-17 07:01
Hi, thanks for your answer.
- pgbackrest_exporter version: v0.7.0
-  If i start pgbackrest_exporter from binary file  the error is not  reproduced
[pgbackrest_exporter.service.txt](https://github.com/woblerr/pgbackrest_exporter/files/7183364/pgbackrest_exporter.service.txt)
[etc_default_pgbackrest_exporter.txt](https://github.com/woblerr/pgbackrest_exporter/files/7183365/etc_default_pgbackrest_exporter.txt)
[pgbackrest_info.json.txt](https://github.com/woblerr/pgbackrest_exporter/files/7183366/pgbackrest_info.json.txt)

**Comment by woblerr** [comment] 2021-09-17 16:14
## Workaround

It's enough to rename the variable `GBACKREST_EXPORTER_OPTS`, for example, to `EXPORT_OPTS`.

```bash
# etc_default_pgbackrest_exporter.txt
EXPORTER_OPTS=--prom.port="9104" --backrest.config="/etc/pgbackrest/pgbackrest.conf" --verbose.info

# pgbackrest_exporter.service.txt
ExecStart=/usr/bin/pgbackrest_exporter $EXPORTER_OPTS
```

## Problem description

The problem is related to passing environment variables to `pgbackrest` and combining `stderr and stdout` from  `pgbackrest` command execution.

By default, prefix for environment variables for `pgbackrest` is  `PGBACKREST_` [parse.c#L47](https://github.com/pgbackrest/pgbackrest/blob/c38d6926d6c9aa01b895a28e66fc0aa6965350a3/src/config/parse.c#L47).

So, `pgbackrest` takes `PGBACKREST_EXPORTER_OPTS` as environment variable and outputs an error:
```bash
$ export PGBACKREST_EXPORTER_OPTS="--stanza=demo" &&  pgbackrest info $PGBACKREST_EXPORTER_OPTS

WARN: environment contains invalid option 'exporter-opts'
stanza: demo
    status: ok
    cipher: none

    db (current)
        wal archive min/max (13): 000000010000000000000001/000000010000000000000002

        full backup: 20210917-144859F
            timestamp start/stop: 2021-09-17 14:48:59 / 2021-09-17 14:49:02
            wal start/stop: 000000010000000000000002 / 000000010000000000000002
            database size: 23.2MB, database backup size: 23.2MB
            repo1: backup set size: 2.8MB, backup size: 2.8MB
```

Since the `CombinedOutput`method [backrest_parser.go#L210](https://github.com/woblerr/pgbackrest_exporter/blob/9793f6e7bf7c08a30c72638470ee3ab7d86a8177/backrest/backrest_parser.go#L210) is currently used, the output with `WARN` is passed on.

It will be fixed in the next release.

Thanks!

**Comment by Nosreme1** [comment] 2021-09-20 13:59
Thanks for the workaround.
I have an other question, i use Consul to discover my exporters but pgbackrest_exporter does not expose "/health" path.
Example for Node Exporter:

# curl $(hostname):9100/health
<html>
                        <head><title>Node Exporter</title></head>
                        <body>
                        <h1>Node Exporter</h1>
                        <p><a href="/metrics">Metrics</a></p>
                        </body>
                        </html>

Thanks

**Comment by woblerr** [comment] 2021-09-20 23:06
Yes, it makes sense to add a simple home page. I put it in a separate issue #12 .

**Closed** 2021-09-23 20:15 UTC
Labels: bug, question
